language: 'ko-KR'
early_access: false
reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: false
  collapse_walkthrough: false
  sequence_diagrams: false
  changed_files_summary: false
  path_filters: ['!.github/**', '!dist/**', '!.src/**', '!./**']
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: false
