name: 'Chromatic'

on:
  push:
    branches: [ develop ]  
  pull_request:
    branches: [ develop ]  

permissions:
  contents: read
  pull-requests: write

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          autoAcceptChanges: 'develop'  
          onlyChanged: true
