name: PR Auto Assign and Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:

  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/FC-DEV-FinalProject/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: feat, setting, fix, docs, refactor, test
          label-operator: OR

  auto-assign:
    runs-on: ubuntu-22.04
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'

  labeler:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
